name: Run docker image

description: execute a specific docker image with its entry point.

inputs:
  docker-image:
    description: the image downloaded
    required: true
  controller-forward-port:
    description: the entry port to interact with the pinot controller
    required: true
  broker-forward-port:
    description: the entry port to interact with the pinot broker
    required: true
  arguments:
    description: arguments passed into the docker image start up script
    required: false

runs:
  using: composite
  steps:
    - name: Run Docker image
      shell: bash
      env:
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        CONTROLLER_PORT_FORWARD: ${{ inputs.controller-forward-port }}
        BROKER_PORT_FORWARD: ${{ inputs.broker-forward-port }}
        ARGS: ${{ inputs.arguments }}
      run: |
        docker run -p "${CONTROLLER_PORT_FORWARD}:${CONTROLLER_PORT_FORWARD}" -p "${BROKER_PORT_FORWARD}:${BROKER_PORT_FORWARD}" -d "${DOCKER_IMAGE}" ${ARGS}
